Repository n00b-coder9/Fark, pull requests merged in 2020-10, with the labels that each got.

#6 Frontend setup
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/App.test.js
  client/src/components/Navigation.js
  client/src/components/form/Button.js
  client/src/components/form/Input.js
  client/src/graphQl/queries/loginQuery.js
  client/src/graphQl/queries/signupQuery.js
  client/src/index.js
  client/src/pages/Feed.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
  client/src/redux/actionTypes.js
  client/src/redux/rootReducer.js
  client/src/redux/slices/drawer.js
  client/src/serviceWorker.js
  client/src/theme.js
  client/src/validator/index.js
  server/.eslintrc.json
  server/graphQl/resolvers.js
  server/graphQl/schema.js
  server/index.js
  server/models/Url.js
  server/models/User.js
  server/validator/index.js
Labels: UI

#7 Auth improvements
  client/src/graphQl/queries/loginQuery.js
  client/src/graphQl/queries/signupQuery.js
  server/graphQl/resolvers.js
  server/graphQl/schema.js
  server/index.js
  server/models/User.js
  server/validator/index.js
Labels: enhancement

#8 Auth
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Navigation.js
  client/src/components/PrivateRoute.js
  client/src/components/auth/Login.js
  client/src/components/auth/Logout.js
  client/src/components/auth/Register.js
  client/src/components/auth/index.js
  client/src/components/common/Snackbar.js
  client/src/components/form/Input.js
  client/src/graphQl/queries/signupQuery.js
  client/src/index.css
  client/src/index.js
  client/src/pages/Feed.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
  client/src/redux/actionTypes.js
  client/src/redux/rootReducer.js
  client/src/redux/slices/auth.js
  client/src/redux/slices/snackbar.js
  client/src/utils/axios.js
  client/src/utils/validator/index.js
  client/src/validator/index.js
  server/graphQl/resolvers.js
  server/index.js
  server/validator/index.js
Labels: UI

#9 add: home page UI
  .gitignore
  client/.eslintrc.json
  client/src/App.js
  client/src/components/auth/index.js
  client/src/components/home/index.js
  client/src/graphQl/queries/shortenUrlQuery.js
  client/src/index.js
  client/src/redux/selectors/index.js
  client/src/redux/slices/auth.js
  client/src/utils/validator/index.js
  package-lock.json
  package.json
  server/.eslintrc.json
  server/graphQl/resolvers.js
  server/graphQl/schema.js
  server/index.js
  server/middleware/auth.js
  server/models/Url.js
  server/utils/urlShortener.js
  server/validator/index.js
Labels: UI

#10 Fix login and drawer issues
  client/src/App.js
  client/src/components/Navigation.js
  client/src/components/auth/Login.js
  client/src/components/auth/Register.js
  client/src/components/auth/index.js
  client/src/components/home/index.js
  client/src/graphQl/queries/shortenUrlQuery.js
  client/src/utils/axios.js
  server/graphQl/resolvers.js
Labels: UI, bug, enhancement

#11 Update homepage UI
  client/src/components/home/index.js
  client/src/utils/validator/index.js
Labels: UI

#13 add: url details addition and update logic
  client/src/components/home/index.js
  client/src/graphQl/queries/addDetailsQuery.js
  client/src/graphQl/queries/shortenUrlQuery.js
  client/src/redux/slices/auth.js
  server/graphQl/resolvers.js
  server/graphQl/schema.js
  server/index.js
  server/middleware/auth.js
  server/models/Url.js
  server/package-lock.json
  server/package.json
Labels: UI
